from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any


SENSITIVE_HEADERS = {
    "authorization",
    "cookie",
    "set-cookie",
    "x-api-key",
    "x-auth-token",
}

SENSITIVE_KEYS = {
    "access_token",
    "refresh_token",
    "id_token",
    "token",
    "password",
    "email",
    "firstName",
    "lastName",
    "phone",
    "address",
}

DEFAULT_HOST_PATTERNS = [
    "orangetheory",
    "otf",
    "mindbody",
]


def redact_value(key: str, value: Any) -> Any:
    if key.lower() in {item.lower() for item in SENSITIVE_KEYS}:
        return "[REDACTED]"
    if isinstance(value, dict):
        return {child_key: redact_value(child_key, child_value) for child_key, child_value in value.items()}
    if isinstance(value, list):
        return [redact_value(key, item) for item in value]
    return value


def redact_json(data: Any) -> Any:
    if isinstance(data, dict):
        return {key: redact_value(key, value) for key, value in data.items()}
    if isinstance(data, list):
        return [redact_json(item) for item in data]
    return data


def redact_headers(headers: dict[str, str]) -> dict[str, str]:
    redacted = {}
    for key, value in headers.items():
        redacted[key] = "[REDACTED]" if key.lower() in SENSITIVE_HEADERS else value
    return redacted


def maybe_json(text: str) -> Any:
    if not text:
        return None
    try:
        return redact_json(json.loads(text))
    except json.JSONDecodeError:
        return text[:2000]


def load_flows(path: Path):
    try:
        from mitmproxy import io
    except ImportError:
        print("mitmproxy is required to read flow files.")
        print("Install dev dependencies with: pip install -r requirements-dev.txt")
        sys.exit(1)

    with path.open("rb") as handle:
        reader = io.FlowReader(handle)
        yield from reader.stream()


def matches_host(host: str, patterns: list[str]) -> bool:
    host = host.lower()
    return any(pattern.lower() in host for pattern in patterns)


def flow_record(flow) -> dict[str, Any]:
    request = flow.request
    response = flow.response
    request_text = request.get_text(strict=False) if request.content else ""
    response_text = response.get_text(strict=False) if response and response.content else ""

    return {
        "method": request.method,
        "url": request.pretty_url,
        "host": request.host,
        "path": request.path,
        "status_code": response.status_code if response else None,
        "request_headers": redact_headers(dict(request.headers)),
        "request_body": maybe_json(request_text),
        "response_headers": redact_headers(dict(response.headers)) if response else {},
        "response_body": maybe_json(response_text),
    }


def classify(record: dict[str, Any]) -> str:
    haystack = f"{record['url']} {json.dumps(record.get('request_body'), default=str)[:500]}".lower()
    if re.search(r"login|auth|oauth|token|session", haystack):
        return "auth"
    if re.search(r"booking|booked|reservation|schedule|class", haystack):
        return "bookings"
    if re.search(r"workout|summary|performance|heart|splat|calorie", haystack):
        return "workouts"
    if re.search(r"profile|member|account|user", haystack):
        return "profile"
    return "other"


def write_markdown(output: Path, grouped: dict[str, list[dict[str, Any]]]) -> None:
    lines = [
        "# Captured OTF API Draft",
        "",
        "Generated by `scripts/extract_otf_flows.py`.",
        "Review manually before moving details into `api-spec.md`.",
        "",
    ]
    for group, records in grouped.items():
        lines.extend([f"## {group.title()}", ""])
        for index, record in enumerate(records, start=1):
            lines.extend(
                [
                    f"### {index}. {record['method']} {record['path']}",
                    "",
                    f"- URL: `{record['url']}`",
                    f"- Status: `{record['status_code']}`",
                    "",
                    "Request headers:",
                    "",
                    "```json",
                    json.dumps(record["request_headers"], indent=2),
                    "```",
                    "",
                    "Request body:",
                    "",
                    "```json",
                    json.dumps(record["request_body"], indent=2, default=str),
                    "```",
                    "",
                    "Response body:",
                    "",
                    "```json",
                    json.dumps(record["response_body"], indent=2, default=str),
                    "```",
                    "",
                ]
            )
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract likely OTF API calls from a mitmproxy flow file.")
    parser.add_argument("flow_file")
    parser.add_argument("--output", default="./api-spec.captured.md")
    parser.add_argument("--host-pattern", action="append", dest="host_patterns")
    args = parser.parse_args()

    flow_file = Path(args.flow_file).resolve()
    if not flow_file.exists():
        print(f"Flow file not found: {flow_file}")
        sys.exit(1)

    patterns = args.host_patterns or DEFAULT_HOST_PATTERNS
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for flow in load_flows(flow_file):
        if not getattr(flow, "request", None):
            continue
        if not matches_host(flow.request.host, patterns):
            continue
        record = flow_record(flow)
        grouped[classify(record)].append(record)

    output = Path(args.output).resolve()
    write_markdown(output, grouped)
    total = sum(len(records) for records in grouped.values())
    print(f"Extracted {total} matching flows to {output}")
    if total == 0:
        print("No matching hosts found. Try rerunning with --host-pattern <domain fragment>.")


if __name__ == "__main__":
    main()
